Encryption methods
FPStruck/Team-5-Project pull request #27
Opened 2023-08-20 10:41 UTC by FPStruck

Please run the code and let me know of any errors. I have tested as much as I can but I know there may be something I missed

2023-08-21 00:57 UTC, TitanSri submitted a review, later dismissed

2023-08-21 00:57 UTC, TitanSri commented on UHDD/src/application/fxmlScenes/PatientInfoView.fxml
This is an old file that is no longer in use

2023-08-21 00:57 UTC, TitanSri commented on UHDD/src/application/viewControllers/DashboardController.java
Verified that this scene is no longer seen in the application.

2023-08-21 00:57 UTC, TitanSri commented on UHDD/src/application/viewControllers/PatientDirectoryController.java
The structure of the main is different for the file location, ie. 
UHDD/src/application/viewControllers/application/viewControllers)
/PatientDirectoryController.java

2023-08-21 00:57 UTC, TitanSri commented on UHDD/src/application/viewControllers/PatientInfoViewController.java
Verified that this scene is no longer seen in the application.

2023-08-21 01:50 UTC, TitanSri reviewed
The new user creation is presenting the same issue with emailing the new user. However, it works fine on from the main. 
Apart from the new user creation, everything seems fine

2023-08-21 01:50 UTC, TitanSri commented on UHDD/src/application/fxmlScenes/Dashboard.fxml
Works fine

2023-08-21 01:50 UTC, TitanSri commented on UHDD/src/application/fxmlScenes/PatientDirectory.fxml
Works fine

2023-08-21 01:50 UTC, TitanSri commented on UHDD/src/application/DBConnector.java
No longer in use on main

2023-08-21 01:50 UTC, TitanSri commented on UHDD/src/application/viewControllers/DashboardController.java
> +							    String name =  patientDetails.getString("FirstName") + " "
No longer in use in main

2023-08-21 01:50 UTC, TitanSri commented on UHDD/src/application/viewControllers/PatientInformationController.java
No longer in user in the application

2023-08-21 01:50 UTC, TitanSri commented on UHDD/src/application/viewControllers/PatientInfoViewController.java
> +
This is no longer in Mina's branch

2023-08-21 01:50 UTC, TitanSri commented on UHDD/src/application/DBConnector.java
> +			PreparedStatement statement = connection.prepareStatement(sql);
I failed to create a new user.
Error: "email failed to send"
Some one else needs to test the new user creation

2023-08-21 01:50 UTC, TitanSri commented on UHDD/src/application/DBConnector.java
> +			String sql = "INSERT INTO testdb.patient_notes (patientId, doctorId, noteText, noteEnteredDate, scriptIncluded) VALUES (?, ?, ?, ?, ?)";
This is not working, this maybe the user session

2023-08-21 01:50 UTC, TitanSri commented on UHDD/src/application/DBConnector.java
> +			    String firstName, String middleName, String lastName, String gender,
Create patient test fine

2023-08-21 01:50 UTC, TitanSri commented on UHDD/src/application/DBConnector.java
> +		public void CreateNewProgressPlanExecuteQuery(String diagnosisId, String initialDetails, String progressPlanGoal, String expectedRemediationDate) throws SQLException{
Works fine

2023-08-21 01:50 UTC, TitanSri commented on UHDD/src/application/DBConnector.java
> +		public ResultSet QueryReturnResultsForUserSession(String username) throws SQLException {
Works fine

2023-08-21 01:50 UTC, TitanSri commented on UHDD/src/application/DBConnector.java
> +		public ResultSet QueryReturnResultsMedicationFromPatientId(String patientId) throws SQLException {
Looks fine

2023-08-21 01:50 UTC, TitanSri commented on UHDD/src/application/DataEncryptorDecryptor.java
> +public class DataEncryptorDecryptor {
tested fine

2023-08-21 01:50 UTC, TitanSri commented on UHDD/src/application/viewControllers/application/viewControllers/PatientDirectoryController.java
> -=======
application seems to be navigating fine

2023-08-21 01:55 UTC, TitanSri requested changes
We need to find out why the email is not sending than I will approve the pull request

2023-08-21 04:16 UTC, Losh19 reviewed
Looks all good but idk if we should merge it until the decryption issue is sorted

2023-08-21 08:22 UTC, TitanSri commented
> We need to find out why the email is not sending than I will approve the pull request

The Email Manager needs more parameters. I will push from Toby's branch

2023-08-21 08:25 UTC, TitanSri approved these changes
Looks good I got the email to work. 
The patient data are working

2023-08-21 08:27 UTC, merged

2023-08-28 21:42 UTC, TitanSri commented
I am not sure why the paths skipped through empty folders for the view controllers.
UHDD/src/application/viewControllers/application/viewControllers